package com.pl.robert;

import java.sql.*;
import java.util.*;
import com.pl.robert.*;

public class PersonManager {

	private Connection conn;
	private Statement stmt;
	private PreparedStatement addPersonStmt;
	private PreparedStatement getPersonStmt;
	private PreparedStatement deletePersonStmt;

	public PersonManager() 
	{
		try 
		{
			conn = DriverManager
					.getConnection("jdbc:hsqldb:hsql://localhost/workdb");

			stmt = conn.createStatement();
			boolean personTableExists = false;

			ResultSet rs = conn.getMetaData().getTables(null, null, null, null);

			while (rs.next()) 
			{
				if ("Person".equalsIgnoreCase(rs.getString("TABLE_NAME"))) 
				{
					personTableExists = true;
					break;
				}
			}

			if (!personTableExists) 
			{
				stmt.executeUpdate(""
						+ "CREATE TABLE person("
						+ "id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
						+ "name varchar(20)," + "" + ")");
			}

			addPersonStmt = conn.prepareStatement("INSERT INTO person (name) VALUES (?)");

			getPersonStmt = conn.prepareStatement("SELECT * FROM person");
			
			deletePersonStmt = conn.prepareStatement("DELETE FROM person");

		} 
		catch (SQLException e) 
		{

			e.printStackTrace();
		}
	}

	public void addPerson(Person person) 
	{
		try 
		{
			addPersonStmt.setString(1, person.getName());
			addPersonStmt.executeUpdate();
		} 
		catch (SQLException e) 
		{

			e.printStackTrace();
		}

	}

	
	public void clearAllPerson() 
	{
		try 
		{
			deletePersonStmt.executeUpdate();
		} 
		catch (SQLException e) 
		{
			e.printStackTrace();
		}
	}

}
